export const SCENE_KEYS = {
  BOOT: 'BOOT',
  TITLE: 'TITLE',
  MAIN_MENU: 'MAIN_MENU',
  STAGE_SELECT: 'STAGE_SELECT',
  STAGE_PLAY: 'STAGE_PLAY',
  RESULT: 'RESULT',
  TUNING: 'TUNING',
  CREDITS: 'CREDITS',
} as const
